# Site settings
name: Alison Hayes
email: alison.s.hayes@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, PHP, MySQL, HTML/CSS, JavaScript, Startups, Agile, Pair Programming"
skills: "Software Developer based in Denver, CO"
baseurl:

social:
  - title: linkedin
    url: https://www.linkedin.com/in/alisonshayes/
  - title: twitter
    url: https://twitter.com/alhayes31

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: cac7f9
  primary-rgb: "202, 199, 249"
  secondary: F4F4FD
  secondary-dark: 29455b
  section-tout: eaf1f1

# Build settings
markdown: kramdown
permalink: pretty
