# Site settings
name: Alison Hayes
email: alison.s.hayes@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, PHP, MySQL, HTML/CSS, JavaScript, Startups, Agile, Pair Programming"
skills: "Software Developer based in Denver, CO"
baseurl:

social:
  - title: linkedin
    url: https://www.linkedin.com/in/alisonshayes/
  - title: twitter
    url: https://twitter.com/alhayes31

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 87ad8f
  primary-rgb: "135, 173, 143"
  secondary: dcd7dd
  secondary-dark: 99c9ef
  section-tout: eaf1f1

# Build settings
markdown: kramdown
permalink: pretty
